import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://images.petz.com.br/fotos/1669739206170.jpg",
    titulo: "Macacão Soft Rosa para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "99.99",
    tipo: "cachorro",
    categoria: "roupas",
  },
  {
    img: "https://images.petz.com.br/fotos/1712847005349.jpg",
    titulo: "Macacão Soft Arco-Irís para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "99.99",
    tipo: "cachorro",
    categoria: "roupas",
  },
  {
    img: "https://images.petz.com.br/fotos/1712847610482.jpg",
    titulo: "Macacão Soft Raposa Marinho para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "99.99",
    tipo: "cachorro",
    categoria: "roupas",
  },
  {
    img: "https://images.petz.com.br/fotos/1672772018766.jpg",
    titulo: "Fantasia de Dinossauro para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "79.90",
    tipo: "gato",
    categoria: "roupas",
  },
  {
    img: "https://images.petz.com.br/fotos/1679588342027.jpg",
    titulo: "Fantasia de Vaca para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "79.90",
    tipo: "gato",
    categoria: "roupas",
  },
  {
    img: "https://images.petz.com.br/fotos/1582822321392.jpg",
    titulo: "Brinquedo Pet Bola para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "7.99",
    tipo: "cachorro",
    categoria: "brinquedo",
  },
  {
    img: "https://images.petz.com.br/fotos/1600364353771.jpg",
    titulo: "Brinquedo Napi Mordedor Galinha para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "8.99",
    tipo: "cachorro",
    categoria: "brinquedo",
  },
  {
    img: "https://images.petz.com.br/fotos/1571773121029.jpg",
    titulo: "Brinquedo Arranhador para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "500.00",
    tipo: "gato",
    categoria: "brinquedo",
  },
  {
    img: "https://images.petz.com.br/fotos/1698343934870.jpg",
    titulo: "Arranhador Cacto para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "289.99",
    tipo: "gato",
    categoria: "brinquedo",
  },
  {
    img: "https://images.petz.com.br/fotos/1679063610869.jpg",
    titulo: "Coleira Toh Fiji para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "39.99",
    tipo: "gato",
    categoria: "acessorios",
  },
  {
    img: "https://images.petz.com.br/fotos/1618433548651.jpg",
    titulo: "Coleira Modernpet Elástica para Gatos",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "49.99",
    tipo: "gato",
    categoria: "acessorios",
  },
  {
    img: "https://images.petz.com.br/fotos/1679321059128.jpg",
    titulo: "Coleira Toh para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "39.99",
    tipo: "cachorro",
    categoria: "acessorios",
  },
  {
    img: "https://images.petz.com.br/fotos/1676484055945.jpg",
    titulo: "Coleira Petz Flúor Orange para Cães",
    avaliaçao: <AiFillStar className="rating-star" />,
    comentarios: "(123 reviews)",
    Preco: "49.99",
    tipo: "cachorro",
    categoria: "acessorios",
  },
];

export default data;
